window.esdocSearchIndex = [
  [
    "webcom-reach/src/core/invite.js~invite",
    "class/src/core/Invite.js~Invite.html",
    "<span>Invite</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Invite.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/reach.js~reach",
    "class/src/Reach.js~Reach.html",
    "<span>Reach</span> <span class=\"search-result-import-path\">webcom-reach/src/Reach.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/room.js~room",
    "class/src/core/Room.js~Room.html",
    "<span>Room</span> <span class=\"search-result-import-path\">webcom-reach/src/core/Room.js</span>",
    "class"
  ],
  [
    "webcom-reach/src/core/user.js~user",
    "class/src/core/User.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">webcom-reach/src/core/User.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/reach.js",
    "file/src/Reach.js.html",
    "src/Reach.js",
    "file"
  ],
  [
    "src/reach.js~reach#anonymous",
    "class/src/Reach.js~Reach.html#instance-method-anonymous",
    "src/Reach.js~Reach#anonymous",
    "method"
  ],
  [
    "src/reach.js~reach#config",
    "class/src/Reach.js~Reach.html#instance-member-config",
    "src/Reach.js~Reach#config",
    "member"
  ],
  [
    "src/reach.js~reach#constructor",
    "class/src/Reach.js~Reach.html#instance-constructor-constructor",
    "src/Reach.js~Reach#constructor",
    "method"
  ],
  [
    "src/reach.js~reach#login",
    "class/src/Reach.js~Reach.html#instance-method-login",
    "src/Reach.js~Reach#login",
    "method"
  ],
  [
    "src/reach.js~reach#logout",
    "class/src/Reach.js~Reach.html#instance-method-logout",
    "src/Reach.js~Reach#logout",
    "method"
  ],
  [
    "src/reach.js~reach#on",
    "class/src/Reach.js~Reach.html#instance-method-on",
    "src/Reach.js~Reach#on",
    "method"
  ],
  [
    "src/reach.js~reach#register",
    "class/src/Reach.js~Reach.html#instance-method-register",
    "src/Reach.js~Reach#register",
    "method"
  ],
  [
    "src/reach.js~reach#rooms",
    "class/src/Reach.js~Reach.html#instance-method-rooms",
    "src/Reach.js~Reach#rooms",
    "method"
  ],
  [
    "src/reach.js~reach#status",
    "class/src/Reach.js~Reach.html#instance-set-status",
    "src/Reach.js~Reach#status",
    "member"
  ],
  [
    "src/reach.js~reach#status",
    "class/src/Reach.js~Reach.html#instance-get-status",
    "src/Reach.js~Reach#status",
    "member"
  ],
  [
    "src/reach.js~reach#users",
    "class/src/Reach.js~Reach.html#instance-method-users",
    "src/Reach.js~Reach#users",
    "method"
  ],
  [
    "src/reach.js~reach.browserdetails",
    "class/src/Reach.js~Reach.html#static-get-browserDetails",
    "src/Reach.js~Reach.browserDetails",
    "member"
  ],
  [
    "src/reach.js~reach.e",
    "class/src/Reach.js~Reach.html#static-get-e",
    "src/Reach.js~Reach.e",
    "member"
  ],
  [
    "src/reach.js~reach.t",
    "class/src/Reach.js~Reach.html#static-get-t",
    "src/Reach.js~Reach.t",
    "member"
  ],
  [
    "src/reach.js~reach.v",
    "class/src/Reach.js~Reach.html#static-get-v",
    "src/Reach.js~Reach.v",
    "member"
  ],
  [
    "src/adapter.js",
    "file/src/adapter.js.html",
    "src/adapter.js",
    "file"
  ],
  [
    "src/constants.js",
    "file/src/constants.js.html",
    "src/constants.js",
    "file"
  ],
  [
    "src/core/invite.js",
    "file/src/core/Invite.js.html",
    "src/core/Invite.js",
    "file"
  ],
  [
    "src/core/invite.js~invite#accept",
    "class/src/core/Invite.js~Invite.html#instance-method-accept",
    "src/core/Invite.js~Invite#accept",
    "method"
  ],
  [
    "src/core/invite.js~invite#cancel",
    "class/src/core/Invite.js~Invite.html#instance-method-cancel",
    "src/core/Invite.js~Invite#cancel",
    "method"
  ],
  [
    "src/core/invite.js~invite#from",
    "class/src/core/Invite.js~Invite.html#instance-get-from",
    "src/core/Invite.js~Invite#from",
    "member"
  ],
  [
    "src/core/invite.js~invite#isaccepted",
    "class/src/core/Invite.js~Invite.html#instance-get-isAccepted",
    "src/core/Invite.js~Invite#isAccepted",
    "member"
  ],
  [
    "src/core/invite.js~invite#iscanceled",
    "class/src/core/Invite.js~Invite.html#instance-get-isCanceled",
    "src/core/Invite.js~Invite#isCanceled",
    "member"
  ],
  [
    "src/core/invite.js~invite#isongoing",
    "class/src/core/Invite.js~Invite.html#instance-get-isOnGoing",
    "src/core/Invite.js~Invite#isOnGoing",
    "member"
  ],
  [
    "src/core/invite.js~invite#isrejected",
    "class/src/core/Invite.js~Invite.html#instance-get-isRejected",
    "src/core/Invite.js~Invite#isRejected",
    "member"
  ],
  [
    "src/core/invite.js~invite#reason",
    "class/src/core/Invite.js~Invite.html#instance-get-reason",
    "src/core/Invite.js~Invite#reason",
    "member"
  ],
  [
    "src/core/invite.js~invite#reject",
    "class/src/core/Invite.js~Invite.html#instance-method-reject",
    "src/core/Invite.js~Invite#reject",
    "method"
  ],
  [
    "src/core/invite.js~invite#room",
    "class/src/core/Invite.js~Invite.html#instance-get-room",
    "src/core/Invite.js~Invite#room",
    "member"
  ],
  [
    "src/core/invite.js~invite#status",
    "class/src/core/Invite.js~Invite.html#instance-get-status",
    "src/core/Invite.js~Invite#status",
    "member"
  ],
  [
    "src/core/invite.js~invite#to",
    "class/src/core/Invite.js~Invite.html#instance-get-to",
    "src/core/Invite.js~Invite#to",
    "member"
  ],
  [
    "src/core/room.js",
    "file/src/core/Room.js.html",
    "src/core/Room.js",
    "file"
  ],
  [
    "src/core/room.js~room#invite",
    "class/src/core/Room.js~Room.html#instance-method-invite",
    "src/core/Room.js~Room#invite",
    "method"
  ],
  [
    "src/core/room.js~room#messages",
    "class/src/core/Room.js~Room.html#instance-method-messages",
    "src/core/Room.js~Room#messages",
    "method"
  ],
  [
    "src/core/room.js~room#name",
    "class/src/core/Room.js~Room.html#instance-get-name",
    "src/core/Room.js~Room#name",
    "member"
  ],
  [
    "src/core/room.js~room#on",
    "class/src/core/Room.js~Room.html#instance-method-on",
    "src/core/Room.js~Room#on",
    "method"
  ],
  [
    "src/core/room.js~room#owner",
    "class/src/core/Room.js~Room.html#instance-get-owner",
    "src/core/Room.js~Room#owner",
    "member"
  ],
  [
    "src/core/room.js~room#participants",
    "class/src/core/Room.js~Room.html#instance-method-participants",
    "src/core/Room.js~Room#participants",
    "method"
  ],
  [
    "src/core/room.js~room#publishstream",
    "class/src/core/Room.js~Room.html#instance-method-publishStream",
    "src/core/Room.js~Room#publishStream",
    "method"
  ],
  [
    "src/core/room.js~room#sendmessage",
    "class/src/core/Room.js~Room.html#instance-method-sendMessage",
    "src/core/Room.js~Room#sendMessage",
    "method"
  ],
  [
    "src/core/room.js~room#status",
    "class/src/core/Room.js~Room.html#instance-get-status",
    "src/core/Room.js~Room#status",
    "member"
  ],
  [
    "src/core/room.js~room#streams",
    "class/src/core/Room.js~Room.html#instance-method-streams",
    "src/core/Room.js~Room#streams",
    "method"
  ],
  [
    "src/core/room.js~room#uid",
    "class/src/core/Room.js~Room.html#instance-get-uid",
    "src/core/Room.js~Room#uid",
    "member"
  ],
  [
    "src/core/user.js",
    "file/src/core/User.js.html",
    "src/core/User.js",
    "file"
  ],
  [
    "src/core/user.js~user#invite",
    "class/src/core/User.js~User.html#instance-method-invite",
    "src/core/User.js~User#invite",
    "method"
  ],
  [
    "src/core/user.js~user#name",
    "class/src/core/User.js~User.html#instance-get-name",
    "src/core/User.js~User#name",
    "member"
  ],
  [
    "src/core/user.js~user#status",
    "class/src/core/User.js~User.html#instance-get-status",
    "src/core/User.js~User#status",
    "member"
  ],
  [
    "src/definitions/browserdetails.js",
    "file/src/definitions/BrowserDetails.js.html",
    "src/definitions/BrowserDetails.js",
    "file"
  ],
  [
    "src/definitions/browserdetails.js~browserdetails",
    "typedef/index.html#static-typedef-BrowserDetails",
    "src/definitions/BrowserDetails.js~BrowserDetails",
    "typedef"
  ],
  [
    "src/definitions/events.js",
    "file/src/definitions/Events.js.html",
    "src/definitions/Events.js",
    "file"
  ],
  [
    "src/definitions/events.js~events",
    "typedef/index.html#static-typedef-Events",
    "src/definitions/Events.js~Events",
    "typedef"
  ],
  [
    "src/definitions/iceserver.js",
    "file/src/definitions/ICEServer.js.html",
    "src/definitions/ICEServer.js",
    "file"
  ],
  [
    "src/definitions/iceserver.js~iceserver",
    "typedef/index.html#static-typedef-ICEServer",
    "src/definitions/ICEServer.js~ICEServer",
    "typedef"
  ],
  [
    "src/definitions/reachconfig.js",
    "file/src/definitions/ReachConfig.js.html",
    "src/definitions/ReachConfig.js",
    "file"
  ],
  [
    "src/definitions/reachconfig.js~reachconfig",
    "typedef/index.html#static-typedef-ReachConfig",
    "src/definitions/ReachConfig.js~ReachConfig",
    "typedef"
  ],
  [
    "src/definitions/streamtypes.js",
    "file/src/definitions/StreamTypes.js.html",
    "src/definitions/StreamTypes.js",
    "file"
  ],
  [
    "src/definitions/streamtypes.js~streamtypes",
    "typedef/index.html#static-typedef-StreamTypes",
    "src/definitions/StreamTypes.js~StreamTypes",
    "typedef"
  ],
  [
    "src/external/element.js",
    "file/src/external/Element.js.html",
    "src/external/Element.js",
    "file"
  ],
  [
    "src/external/element.js~element",
    "external/index.html",
    "src/external/Element.js~Element",
    "external"
  ],
  [
    "src/external/webcom.js",
    "file/src/external/Webcom.js.html",
    "src/external/Webcom.js",
    "file"
  ],
  [
    "src/external/webcom.js~webcom",
    "external/index.html",
    "src/external/Webcom.js~Webcom",
    "external"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]